<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <Configurations>Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>Regl</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Dockerfile"/>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TextCopy" Version="6.2.1"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="src\*.fs"/>
    </ItemGroup>

    <ItemGroup>
        <!--IO-->
        <Compile Include="src\CommandLine\IO\LinesBuffer.fs"/>
        <Compile Include="src\CommandLine\IO\InOut.fs"/>
        <!--IO-->

        <!--CLI - Types-->
            <!--CLI - Types - Flags-->
            <Compile Include="src\CommandLine\Types\FlagParseResult.fs"/>
            <Compile Include="src\CommandLine\Types\FlagsAndParams\ArgVal.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\FlagValSet.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\BoolFlag.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\StringFlag.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\Flags.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\IParam.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\Param.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\RegexParam.fs" />
            <Compile Include="src\CommandLine\Types\FlagsAndParams\IntParam.fs" />
            <!--CLI - Types - Flags-->

        <Compile Include="src\CommandLine\Types\CommandParseResult.fs"/>
        <Compile Include="src\CommandLine\Types\CommandBody.fs"/>

        <Compile Include="src\CommandLine\Types\Arguments\Args.fs" />
        <Compile Include="src\CommandLine\Types\Arguments\ArgEntry.fs" />

        <Compile Include="src\CommandLine\Types\Cmds\CmdEntry.fs" />
        <!--CLI - Types-->

        <!--Bash Commands of Gen Command Types-->
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\Lines\Line.fs" />
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\Lines\SourceLine.fs" />
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\*.fsi"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\*.fs"/>
        <!--Bash Commands of Gen Command Types-->
        <!--Types-->

        <!--Shared Functions-->
        <Compile Include="src\CommandLine\Commands\Shared.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Shared.fs"/>
        <!--Shared Functions-->
    </ItemGroup>

    <ItemGroup>
        <!--Bash Commands-->
        <Compile Include="src\CommandLine\Commands\*.fsi"/>
        <Compile Include="src\CommandLine\Commands\*.fs"/>
        <!--Bash Commands-->

        <!--Bash Commands of Gen Command's Subcommands-->
        <Compile Include="src\CommandLine\Commands\GenCommand\AddEvcm.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Copy.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Echo.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\SetEnvar.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\UnsetEnvar.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Tpl.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Import.fs"/>
        <Compile Include="src\CommandLine\Commands\GenCommand\Implementation.fs"/>
        <!--Bash Commands of Gen Command's Subcommands-->
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
    </ItemGroup>

</Project>
