<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <SelfContained>true</SelfContained>
        <PublishSingleFile>true</PublishSingleFile>
        <Configurations>Release</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>Regl</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="Dockerfile"/>
        <Content Include="..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
        <Folder Include="Commands\Shell\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="TextCopy" Version="6.2.1"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="src\CommandLine\Shared.fs"/>

        <Compile Include="src\CommandLine\Types\IFlag.fsi"/>
        <Compile Include="src\CommandLine\Types\IFlag.fs"/>

        <Compile Include="src\CommandLine\Types\IInFlag.fsi"/>
        <Compile Include="src\CommandLine\Types\IInFlag.fs"/>

        <Compile Include="src\CommandLine\Types\OnFlag.fs"/>
        <Compile Include="src\CommandLine\Types\InStringFlag.fs"/>
        <Compile Include="src\CommandLine\Types\ParseResult.fs"/>
        <Compile Include="src\CommandLine\Types\CommandBody.fs"/>

        <Compile Include="src\CommandLine\Types\ICommandBuilder.fsi"/>
        <Compile Include="src\CommandLine\Types\ICommandBuilder.fs"/>
        <Compile Include="src\CommandLine\Builders\CommandBuilder.fs"/>

        <Compile Include="src\CommandLine\Types\Shared.fs"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="src\CommandLine\Commands\Copy.fsi"/>
        <Compile Include="src\CommandLine\Commands\Copy.fs"/>

        <Compile Include="src\CommandLine\Commands\Split.fsi"/>
        <Compile Include="src\CommandLine\Commands\Split.fs"/>

        <Compile Include="src\CommandLine\Commands\Ls.fsi"/>
        <Compile Include="src\CommandLine\Commands\Ls.fs"/>

        <Compile Include="src\CommandLine\Commands\ToFile.fsi"/>
        <Compile Include="src\CommandLine\Commands\ToFile.fs"/>

        <Compile Include="src\CommandLine\Commands\Match.fsi"/>
        <Compile Include="src\CommandLine\Commands\Match.fs"/>

        <Compile Include="src\CommandLine\Commands\RemoveEmpty.fsi"/>
        <Compile Include="src\CommandLine\Commands\RemoveEmpty.fs"/>

        <Compile Include="src\CommandLine\Commands\Gen.fsi"/>
        <Compile Include="src\CommandLine\Commands\Gen.fs"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\GenCommandBody.fsi" />
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\GenCommandBody.fs" />

        <Compile Include="src\CommandLine\Commands\GenCommand\Types\GenCommandBuilder.fsi" />
        <Compile Include="src\CommandLine\Commands\GenCommand\Types\GenCommandBuilder.fs" />

        <Compile Include="src\CommandLine\Commands\GenCommand\Copy.fsi" />
        <Compile Include="src\CommandLine\Commands\GenCommand\Copy.fs" />

        <Content Include="src\CommandLine\Commands\GenCommand\README.md" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>

</Project>
