<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Fnm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="src\Types\NodeCargo.fs" />
        <Compile Include="src\Types\INode.fs" />
        <Compile Include="src\Types\Nodes\AChar.fs" />
        <Compile Include="src\Types\Nodes\WildCard.fs" />
        <Compile Include="src\Types\PatternCargo.fs" />
        <Compile Include="src\Types\Pattern.fs" />
        <Compile Include="src\Types\Builders\PatternBuilder.fs" />
    </ItemGroup>

</Project>
