<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Fnm</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="src\Helper\SubstringRange.fs" />
        <Compile Include="src\Helper\StringHelper.fs" />
        <Compile Include="src\Helper\CharCargo.fs" />
        <Compile Include="src\Helper\StringCargo.fs" />
        
        <Compile Include="src\Pattern\Parse\Delegates.fs" />
        <Compile Include="src\Pattern\Parse\Nodes\WildCard.fs" />
        <Compile Include="src\Pattern\Parse\Nodes\Bracket\CharRange.fs" />
        <Compile Include="src\Pattern\Parse\Nodes\Bracket\Negate.fs" />
        <Compile Include="src\Pattern\Parse\Nodes\Character.fs" />
        <Compile Include="src\Pattern\Parse\Nodes\Any.fs" />
        <Compile Include="src\Pattern\Parse\Trees.fs" />
        
        <Compile Include="src\Types\NodeCargo.fs" />
        <Compile Include="src\Types\PatternCargo.fs" />
        
        <Compile Include="src\Types\INode.fs" />
        <Compile Include="src\Types\Nodes\AChar.fs" />
        <Compile Include="src\Types\Nodes\WildCard.fs" />
        
        <Compile Include="src\Types\Pattern.fs" />
        <Compile Include="src\Types\Matcher.fs" />
        
        <Compile Include="src\Types\Builders\PatternBuilder.fs" />
        <Compile Include="src\Types\Builders\MatchBuilder.fs" />
        <Content Include="refactor.md" />
    </ItemGroup>

</Project>
